server:
  port: 8888

spring:
  data:
    mongodb:
      database: mongodb
  jackson:
    date-format: mm-dd-yyyy HH:mm:ss
    time-zone: GMT-4
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true


